### PR TITLE
Make Prev_target Vector2d

### PR DESCRIPTION
**Pull request by thebhatman**
Prev_target was never really vector2D and checking isinstance was creating a problem. So this patch fixes it.

### CODE REVIEW

**Comment by saurabhkgp21** [comment]
@thebhatman wont it create any bug on first call?

**Comment by thebhatman** [comment]
It doesn't create an error because I have also changed prev_target to be of Vector2D() instead of None. But because of that prev_target will be (0,0) in the very first call. This might cause one unnecessary replan in the beginning. I can change the initialisation of prev_target.

**Comment by saurabhkgp21** [comment]
But what if the target is in the vicinity of (0,0), then it will not replan. That can be a problem in the initialisation of velocity instance.
May be u can initialise prev_target as `Vector2D(-5000,-5000) //any random point outside the field`. Just see this once.

**Comment by thebhatman** [comment]
Closing this because of this change https://github.com/KRSSG/robocup/pull/62.

**Pull request closed without merging**
