### PR TITLE
Cleanup beliefatate

### LINKED ISSUE #19: Remove unwanted variables

### PR DESCRIPTION
**Pull request by shamin1998**
Fixes #19 
Removed: (commented out)
1) opp_bot_marking_our_attacker
2) ball_at_corners
3) ball_in_our_possession

As only belief_state/src/node_class.cpp is being used
and not node.cpp or node1.cpp I've only made changes to node_class.cpp

Hence also commented out the command to compile node.cpp from
belief_state/CMakeLists.txt

### CODE REVIEW

**Comment by saurabhkgp21** [comment]
Remove every predictions other than velocities from beliefstate and add them into utils/state_function.py

**Comment by saurabhkgp21** [comment]
Goalie id of both teams will be taken from referee msg

**Comment by shamin1998** [comment]
Is the referee msg published on any topic?

**Comment by saurabhkgp21** [comment]
yeah...  but it hasnt been integrated with this code-base

**Comment by shamin1998** [comment]
So is there any other way to take goalie ids from referee for now?

Shamin Aggarwal
2nd year Undergraduate
Computer Science and Engineering Department
IIT Kharagpur

**Comment by saurabhkgp21** [comment]
Where do you need goalie id?

**Comment by shamin1998** [comment]
Nah, we don't need it as such. You'd only commented that the goalie id has
to be taken from referee msg.
Else should I just remove it from beliefstate?

Shamin Aggarwal
2nd year Undergraduate
Computer Science and Engineering Department
IIT Kharagpur

**Comment by saurabhkgp21** [comment]
Yeah just comment it for now..  If there will be any need of taking goalie id before integrating referee comm we will uncomment it

**Comment by shamin1998** [comment]
Ok

Shamin Aggarwal
2nd year Undergraduate
Computer Science and Engineering Department
IIT Kharagpur

**Pull request merged**
